### ISSUE TITLE
PostgreSQL positional parameter support

### ISSUE THREAD

**Issue by penberg** [tursodatabase/libsql#107]
One of the annoying differences between SQLite and PostgreSQL is that the latter supports positional parameters for prepared statements with the `$<number>` syntax. Let's add opt-in support to libSQL to support this syntax to make it easier to write SQL that's portable across SQLite and PostgreSQL.

**Comment by psarna** [comment]
@penberg @MarinPostma btw, libSQL already supports `$<name>` syntax: https://www.sqlite.org/lang_expr.html#varparam, which will happen to work exactly as expected if the numbers appear in consecutive order.

It also means that numeric `$` **must** be opt-in, because in theory it can change the semantics of existing programs. It looks like a simple enough change though, `$nnn` should simply be treated the same as `?nnn` already is, if somebody explicitly asks for it with a compilation flag.

**Comment by penberg** [comment]
We no longer are pursuing PostgreSQL compatibility so closing this.
