### ISSUE TITLE
SQLITE_ROW shouldn't be an error as per docs

### ISSUE THREAD

**Issue by tekjar** [tursodatabase/libsql#1322]
https://github.com/tursodatabase/libsql/blob/main/libsql/src/local/statement.rs#L116

Is this supposed to be an error?

From the docs

```
1. Result Codes versus Error Codes
"Error codes" are a subset of "result codes" that indicate that something has gone wrong. There are only a few non-error result codes: [SQLITE_OK](https://www.sqlite.org/rescode.html#ok), [SQLITE_ROW](https://www.sqlite.org/rescode.html#row), and [SQLITE_DONE](https://www.sqlite.org/rescode.html#done). The term "error code" means any result code other than these three.
```
https://www.sqlite.org/rescode.html

**Comment by asg017** [comment]
`.execute()` specifically is meant for SQLite statements that don't return any rows, which is why `Error::ExecuteReturnedRows` exists. It's good for `INSERTs`/`UPDATEs`/`DELETEs`. If you want to return rows, use `.query()` instead. 

The rusqlite docs have a good explanation of this patter: https://docs.rs/rusqlite/0.31.0/rusqlite/struct.Statement.html#method.execute
