### ISSUE TITLE
Random rowid not working

### ISSUE THREAD

**Issue by maekoos** [tursodatabase/libsql#333]
I'm using the latest pre-built binary (0.19.0). I run this from the documentation:
```sql
CREATE TABLE shopping_list(item text, quantity int) RANDOM ROWID;
```

and get the following output (from sqld):

> 2023-08-29T15:33:04.877315Z ERROR tracing_panic: A panic occurred panic.payload="internal error: entered unreachable code" panic.location="/Users/runner/actions-runner/_work/sqld/sqld/target/release/build/sqlite3-parser-daa27c40267ed776/out/parse.rs:573:13"

I'm guessing it has something to do with the `sqlite3-parser`-crate not recognising RANDOM ROWID as valid syntax?

**Comment by CodingDoug** [comment]
Similarly, [altering columns](https://github.com/libsql/libsql/blob/main/doc/libsql_extensions.md#altering-columns) does not parse, but it does not cause a panic.

**Comment by psarna** [comment]
Yes, it's due to `sqlite3-parser`, which build from vanilla SQLite, not libSQL. We should consider one of the following:
a. keep contributing the support, e.g. under a `libsql` feature flag
b. add some kind of extension mechanism to sqlite3-parser to let us dynamically add our syntax extensions
c. fork (last resort)

**Comment by psarna** [comment]
@MarinPostma @LucioFranco fyi, we have more reports of that. We need to consider how to best approach parser extensions
