### ISSUE TITLE
ALTER TABLE ALTER COLUMN not working

### ISSUE THREAD

**Issue by sjunepark** [tursodatabase/libsql#447]
I did as the [docs](https://github.com/tursodatabase/libsql/blob/main/doc/libsql_extensions.md#altering-columns) said, however am getting the error below.
```
→  .schema
CREATE TABLE emails (user_id INT, email TEXT);     
CREATE TABLE users (id INT PRIMARY KEY);           
→  ALTER TABLE emails ALTER COLUMN user_id TO user_id INT REFERENCES users(id);
Error: failed to execute SQL: ALTER TABLE emails ALTER COLUMN user_id TO user_id INT REFERENCES users(id);
SQL string could not be parsed: near ALTER, "None": syntax error at (1, 25)
→   
```
Did I do something wrong?

**Comment by JakeHedman** [comment]
Works on a local file database but not when connecting to a sqld server for me.

**Comment by buzinas** [comment]
Any work-arounds? This is these third time I'm facing this issue in the last few days.

One time I was able to circumvent the issue by doing a lot of manual work using the shell to recreate the table (I couldn't really use Drizzle migrations for this – it doesn't seem to be possible to disable the foreign keys pragma, since each statement runs separately), and this doesn't scale well with CI etc.

The other time I completely wiped the database and start from scratch, since this was easier than any work-around.

But now we are approaching to run things in production, and this is really getting in our way.

**Comment by JakeHedman** [comment]
> Any work-arounds? This is these third time I'm facing this issue in the last few days.
> 
> One time I was able to circumvent the issue by doing a lot of manual work using the shell to recreate the table (I couldn't really use Drizzle migrations for this – it doesn't seem to be possible to disable the foreign keys pragma, since each statement runs separately), and this doesn't scale well with CI etc.
> 
> The other time I completely wiped the database and start from scratch, since this was easier than any work-around.
> 
> But now we are approaching to run things in production, and this is really getting in our way.

I didn't find any real workarounds workarounds, but in my case I just needed to change the data type of a single field so I was able to use drizzle migrations like this:

```sql
ALTER TABLE stickers RENAME COLUMN image TO image_old;
--> statement-breakpoint
ALTER TABLE stickers ADD image blob;
--> statement-breakpoint
UPDATE stickers SET image = image_old;
--> statement-breakpoint
ALTER TABLE stickers DROP COLUMN image_old;
```
